#
# ======== Scoreboard Configurations ========
#
#   Wiki: https://github.com/okocraft/Scoreboard/wiki
#   GitHub: https://github.com/okocraft/Scoreboard/
#
# ===========================================
#

# The maximum length per line.
#
# The length is based on the number of characters actually displayed and is truncated if the limit is exceeded.
# Default: 32
max-line-length: 32
