title:
  interval: 1
  list:
    - "&8&m=====&a&l Server &8&m====="
    - "&8&m=====&b&l Server &8&m====="
    - "&8&m=====&c&l Server &8&m====="
    - "&8&m=====&d&l Server &8&m====="
    - "&8&m=====&e&l Server &8&m====="
    - "&8&m=====&f&l Server &8&m====="

# Built-in placeholders (PlaceholderAPI not required):
# %server_tps% %server_online%
# %player_name% %player_displayname% %player_world% %player_block_x% %player_block_y% %player_block_z% %player_ping%
line:
  empty-1:
    interval: 0
    list:
      - ""
  player-count:
    interval: 5
    list:
      - " &7Login: &b%server_online% players"
  player-ping:
    interval: 20
    list:
      - " &7Ping: &b%player_ping%ms"
  empty-2:
    interval: 0
    list:
      - ""
