#
# The settings of this scoreboard.
#
# (Structure)
# title:
#   interval: <ticks to update the title>
#   length-limit: <the max length of the title, overrides the config.yml setting>
#   list:
#     - "<contents to be displayed>"
#
# lines:
#   <unique name>:
#     interval: <ticks to update this line>
#     length-limit: <the max length of this line, overrides the config.yml setting>
#     list:
#       - "<contents to be displayed>"
#
# If the "interval" is equals or less than 0 or "list" is empty, the title will never be updated.
#
# Contents can be colored by Legacy Color Format (using &a for named colors and styles, or &#xxxxxx for hex colors),
# and placeholders can also be used.
#
# Built-in placeholders:
#
# - %server_tps% - The current server TPS (Ticks Per Second)
# - %server_online% - The current online players
# - %player_name% - The name of the viewer
# - %player_displayname% - The display name of the viewer
# - %player_world% - The name of the world where the viewer is in
# - %player_block_x% - The block x-coordinate of the viewer's location
# - %player_block_y% - The block y-coordinate of the viewer's location
# - %player_block_z% - The block z-coordinate of the viewer's location
# - %player_ping% - The ping of the viewer
#
# Other %-enclosed placeholders are replaced by PlaceholderAPI if available.
#
title:
  interval: 1
  list:
    - "&8&m=====&a&l Server &8&m====="
    - "&8&m=====&b&l Server &8&m====="
    - "&8&m=====&c&l Server &8&m====="
    - "&8&m=====&d&l Server &8&m====="
    - "&8&m=====&e&l Server &8&m====="
    - "&8&m=====&f&l Server &8&m====="

lines:
  empty-1:
    interval: 0
    list: [ ]
  player-count:
    interval: 5
    list:
      - " &7Login: &b%server_online% players"
  player-ping:
    interval: 20
    list:
      - " &7Ping: &b%player_ping%ms"
  empty-2:
    interval: 0
    list: [ ]
